#!/usr/bin/env tsx
/**
 * 把 plugin/ 的 canonical skills 轉成各平台格式。
 *
 *   pnpm plugin:build                產生所有平台
 *   pnpm plugin:build --check        只比對，不寫檔（CI 用，有落差就 exit 1）
 *   pnpm plugin:build --only codex   只產一個平台
 *
 * canonical 只有一份：plugin/skills/。Claude Code 直接載入它，其餘平台都是產物；
 * 產物被手改會被 --check 抓到。
 */

import { createHash } from 'node:crypto'
import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, statSync, writeFileSync } from 'node:fs'
import { dirname, join, normalize, relative, resolve } from 'node:path'

const PLUGIN_ROOT = resolve(import.meta.dirname, '..')
const REPO_ROOT = resolve(PLUGIN_ROOT, '..')
const SKILLS_DIR = join(PLUGIN_ROOT, 'skills')

const BANNER = '<!-- GENERATED by plugin/scripts/build.ts — 不要直接改這個檔案，改 plugin/skills/<name>/ 後重跑 pnpm plugin:build -->'

/** Agent Skills 標準只允許這六個 frontmatter 欄位；多一個，claude.ai 上傳會硬錯。 */
const SPEC_FIELDS = ['name', 'description', 'license', 'compatibility', 'metadata', 'allowed-tools']

type Platform = {
  label: string
  emit: 'native' | 'full-copy' | 'openai-plugin' | 'skill-bundle'
  target: string
  has: string[]
  pluginRoot?: string
  linkMode?: LinkMode
  specClean?: boolean
  descriptionLimit?: number
  note?: string
  gh_note?: string
  hooks_note?: string
  conditional_note?: string
  missing_note?: Record<string, string>
}

type Manifest = {
  capabilities: Record<string, string>
  platforms: Record<string, Platform>
  skills: Record<string, { requires: string[]; optional: string[] }>
}

// 測試要驗證「target 指到 canonical 會被擋下」，但不該為此改寫 repo 裡的 platforms.json——
// vitest 平行跑不同測試檔，改到一半會被另一支正在打包的測試讀到（2026-09-21 就是這樣
// 讓 zip 可重現性測試紅掉）。改用環境變數指向替代 manifest，測試就完全不碰共用狀態。
const MANIFEST_PATH = process.env.DAODAO_PLUGIN_PLATFORMS ?? join(PLUGIN_ROOT, 'platforms.json')
const manifest: Manifest = JSON.parse(readFileSync(MANIFEST_PATH, 'utf8'))
const pluginMeta = JSON.parse(readFileSync(join(PLUGIN_ROOT, '.claude-plugin', 'plugin.json'), 'utf8'))

const errors: string[] = []

// ---------------------------------------------------------------- helpers

function walk(dir: string): string[] {
  return readdirSync(dir).flatMap((e) => {
    const full = join(dir, e)
    return statSync(full).isDirectory() ? walk(full) : [full]
  })
}

function splitFrontmatter(src: string, where: string): { fields: Record<string, string>; order: string[]; body: string } {
  const m = src.match(/^---\n([\s\S]*?)\n---\n?/)
  if (!m) throw new Error(`${where}: SKILL.md 缺少 frontmatter`)
  const fields: Record<string, string> = {}
  const order: string[] = []
  const lines = m[1].split('\n')
  for (let i = 0; i < lines.length; i++) {
    const km = lines[i].match(/^([a-zA-Z][\w-]*):\s*(.*)$/)
    if (!km) continue
    const [, key, rawValue] = km
    order.push(key)
    if (rawValue === '>-' || rawValue === '>' || rawValue === '|') {
      const folded: string[] = []
      while (i + 1 < lines.length && /^\s+\S/.test(lines[i + 1])) folded.push(lines[++i].trim())
      fields[key] = folded.join(' ')
    } else {
      fields[key] = rawValue.replace(/^["']|["']$/g, '')
    }
  }
  return { fields, order, body: src.slice(m[0].length) }
}

/** YAML 單行字串：值裡有冒號或 # 就引號包起來，避免下游 parser 解錯。 */
function yamlLine(key: string, value: string): string {
  const needsQuote = /[:#]|^\s|\s$/.test(value)
  return `${key}: ${needsQuote ? JSON.stringify(value) : value}`
}

function renderFrontmatter(fields: Record<string, string>, order: string[], platform: Platform, skill: string): string {
  const keys = platform.specClean ? order.filter((k) => SPEC_FIELDS.includes(k)) : order
  if (platform.specClean) {
    const dropped = order.filter((k) => !SPEC_FIELDS.includes(k))
    if (dropped.length) errors.push(`${skill} → ${platform.label}：frontmatter 有規格外欄位 ${dropped.join('、')}，已移除但請確認行為不依賴它`)
  }
  const out = keys.map((k) => {
    let v = fields[k]
    if (k === 'description' && platform.descriptionLimit && v.length > platform.descriptionLimit) {
      errors.push(`${skill} → ${platform.label}：description ${v.length} 字，超過上限 ${platform.descriptionLimit}，請在 canonical 縮短`)
    }
    return yamlLine(k, v)
  })
  return `---\n${out.join('\n')}\n---\n`
}

function assess(skill: string, platform: Platform) {
  const spec = manifest.skills[skill]
  if (!spec) throw new Error(`platforms.json 缺少 skill「${skill}」的能力宣告`)
  return {
    included: spec.requires.every((c) => platform.has.includes(c)),
    missingRequired: spec.requires.filter((c) => !platform.has.includes(c)),
    missingOptional: spec.optional.filter((c) => !platform.has.includes(c)),
  }
}

function capLabel(cap: string) {
  return manifest.capabilities[cap] ?? cap
}

function gapSection(platform: Platform, missing: string[], conditional: boolean): string {
  if (missing.length === 0) return ''
  const lead = conditional
    ? [
        `## ⚠ 執行環境落差（${platform.label}）`,
        '',
        '這個 plugin 會同時被有 repo 的 Codex 與沒有 repo 的 ChatGPT 網頁／行動版載入。**先確認你手上有沒有下列能力**；沒有的部分照著做但不要宣稱已完成，改成輸出給人執行的指令，並在交付時明列哪幾項未查證：',
      ]
    : [
        `## ⚠ ${platform.label} 能力落差`,
        '',
        '下列步驟在這個平台上**無法自動完成**。照著做但不要宣稱已完成，改成輸出給人執行的指令，並在交付時明列哪幾項未查證：',
      ]
  return [
    ...lead,
    '',
    ...missing.map((c) => `- **${c}**（${capLabel(c)}）：${platform.missing_note?.[c] ?? `此平台不具備此能力。`}`),
    '',
    '共用原則：查不到的事實標「未查證」，不要用推測補齊；需要授權的動作只做到預覽。',
    '',
    '---',
    '',
  ].join('\n')
}

/**
 * canonical 的連結有三種，各平台要用不同方式處理：
 *
 *   A. plugin 內部：`../../docs/x.md`、`../../templates/x.md`、`../<skill>/SKILL.md`
 *   B. repo 根：`../../../REVIEW.md`、`../../../../scripts/x.md`
 *   C. shell 用的 ${CLAUDE_PLUGIN_ROOT}（只有 Claude Code 會展開）
 *
 * `.agents/skills/<name>/` 跟 canonical 同深度，所以 B 原封不動就是對的；
 * 但 docs/ 與 templates/ 不在 .agents/ 底下，A 要改指回 repo 裡的 plugin/。
 *
 * standalone 包（openai-plugin、web-plugin）自己帶 docs/ 與 templates/，
 * 所以 A 原封不動；B 指到的檔案沒隨包出貨，改寫成說明文字而不是死連結。
 */
type LinkMode = 'in-repo' | 'standalone' | 'flatten'

function rewriteBody(body: string, opts: { pluginRoot: string; mode: LinkMode }): string {
  let out = body.replaceAll('${CLAUDE_PLUGIN_ROOT}', opts.pluginRoot)

  if (opts.mode === 'flatten') {
    return out.replace(/\[([^\]]+)\]\((?:\.\.\/)+([^)]+)\)/g, '**$1**（原始檔 `$2`，此平台無法直接開啟）')
  }

  if (opts.mode === 'in-repo') {
    // A：docs/ 與 templates/ 沒有複製到 .agents/，指回 repo 裡的 canonical
    out = out.replaceAll('](../../docs/', `](../../../${opts.pluginRoot}/docs/`)
    out = out.replaceAll('](../../templates/', `](../../../${opts.pluginRoot}/templates/`)
    // B 與 sibling skill 保持原樣：深度相同，本來就指得到
    return out
  }

  // standalone：A 與 sibling 保持原樣（docs/ 與 templates/ 會一起打包），
  // B 指到的是 repo 檔案，沒出貨，改成說明避免死連結
  return out.replace(/\[([^\]]+)\]\(\.\.\/\.\.\/\.\.\/(?:\.\.\/)*([^)]+)\)/g, '**$1**（repo 檔案 `$2`，未隨本包出貨）')
}

// ---------------------------------------------------------------- emitters

type OutFile = { path: string; content: string }

function skillFiles(platform: Platform, opts: { dir: string; conditional: boolean; copyRefs: boolean }) {
  const files: OutFile[] = []
  const included: string[] = []
  const excluded: { name: string; missing: string[] }[] = []
  const degraded: { name: string; missing: string[] }[] = []
  const pluginRoot = platform.pluginRoot ?? ''
  const mode: LinkMode = platform.linkMode ?? (platform.pluginRoot ? 'in-repo' : 'flatten')

  for (const skill of readdirSync(SKILLS_DIR).sort()) {
    const a = assess(skill, platform)
    if (!a.included) {
      excluded.push({ name: skill, missing: a.missingRequired })
      continue
    }
    included.push(skill)
    const gaps = [...a.missingRequired, ...a.missingOptional]
    if (gaps.length) degraded.push({ name: skill, missing: gaps })

    const src = readFileSync(join(SKILLS_DIR, skill, 'SKILL.md'), 'utf8')
    const { fields, order, body } = splitFrontmatter(src, skill)
    files.push({
      path: join(opts.dir, skill, 'SKILL.md'),
      content:
        renderFrontmatter(fields, order, platform, skill) +
        `\n${BANNER}\n\n` +
        gapSection(platform, gaps, opts.conditional) +
        rewriteBody(body, { pluginRoot, mode }),
    })

    if (opts.copyRefs) {
      const refDir = join(SKILLS_DIR, skill, 'references')
      if (existsSync(refDir)) {
        for (const f of walk(refDir)) {
          const raw = readFileSync(f, 'utf8')
          files.push({
            path: join(opts.dir, skill, relative(join(SKILLS_DIR, skill), f)),
            content: /\.(md|mjs|js|ts|py|json)$/.test(f) ? rewriteBody(raw, { pluginRoot, mode }) : raw,
          })
        }
      }
    }
  }
  return { files, included, excluded, degraded }
}

function statusTable(included: string[], excluded: { name: string; missing: string[] }[], degraded: { name: string; missing: string[] }[]) {
  const degradedMap = new Map(degraded.map((d) => [d.name, d.missing]))
  const rows = [
    ...included.map((n) => `| ${n} | ✅ | ${degradedMap.has(n) ? `降級：${degradedMap.get(n)!.join('、')}` : '完整'} |`),
    ...excluded.map((e) => `| ${e.name} | ❌ | 缺必要能力：${e.missing.join('、')} |`),
  ]
  return ['| Skill | 收錄 | 備註 |', '|---|---|---|', ...rows].join('\n')
}


/** standalone 包要自己帶 docs/ 與 templates/，否則 skill 內的相對連結指不到東西。 */
function bundleSupportFiles(dir: string): OutFile[] {
  const files: OutFile[] = []
  for (const sub of ['docs', 'templates']) {
    const src = join(PLUGIN_ROOT, sub)
    if (!existsSync(src)) continue
    for (const f of walk(src)) {
      files.push({ path: join(dir, sub, relative(src, f)), content: readFileSync(f, 'utf8') })
    }
  }
  return files
}


/**
 * standalone 包的最後一道：任何指不到包內檔案的相對連結，一律降級成說明文字。
 *
 * 光靠字串規則不夠——同一個 `../../docs/x.md` 在 skills/<name>/ 底下指的是 plugin 的 docs，
 * 在 templates/ 底下指的是 repo 的 docs，深度不同意義就不同。與其猜，不如拿實際要輸出的
 * 檔案清單去解析，解不到就代表那個檔案沒隨包出貨，留著只會變成死連結。
 */
function resolveBundleLinks(files: OutFile[], base: string): OutFile[] {
  // f.path 一定以 base 開頭，直接去頭得到包內路徑；用 path.relative 會把相對的 base
  // 先解析到 cwd，算出一串 ../../.. 的假路徑。
  const inBundle = (p: string) => normalize(p.slice(base.length).replace(/^\/+/, ''))
  const emitted = new Set(files.map((f) => inBundle(f.path)))

  return files.map((f) => {
    if (!f.path.endsWith('.md')) return f
    const fromDir = dirname(inBundle(f.path))
    const content = f.content.replace(
      /\[([^\]]+)\]\((\.\.?\/[^)#:]+\.(?:md|mjs|py|json|sh))\)/g,
      (whole, label: string, link: string) => {
        const target = normalize(join(fromDir, link))
        return emitted.has(target) ? whole : `**${label}**（\`${target}\`，未隨本包出貨）`
      },
    )
    return content === f.content ? f : { ...f, content }
  })
}

function buildAgentsSkills(platform: Platform): OutFile[] {
  const { files, included, excluded, degraded } = skillFiles(platform, { dir: platform.target, conditional: false, copyRefs: true })
  files.push({
    path: join(platform.target, 'README.md'),
    content: [
      `# ${platform.label}`,
      '',
      BANNER,
      '',
      'canonical 在 `plugin/skills/`。這裡是完整複本，不是薄入口——`.agents/skills/` 是 Codex 與 ChatGPT 桌面版',
      '實際掃描的目錄（`$CWD`、`$CWD/..`、`$REPO_ROOT` 三層都會掃），內容必須自足。',
      '',
      statusTable(included, excluded, degraded),
      '',
      '## 閘門',
      '',
      platform.hooks_note ?? '',
      '',
      '## 其餘落差',
      '',
      Object.entries(platform.missing_note ?? {}).map(([c, n]) => `- **${c}**：${n}`).join('\n'),
      '',
    ].join('\n'),
  })
  return files
}

function buildOpenAiPlugin(platform: Platform): OutFile[] {
  const { files, included, excluded, degraded } = skillFiles(platform, {
    dir: join(platform.target, 'skills'),
    conditional: true,
    copyRefs: true,
  })

  files.push(...bundleSupportFiles(platform.target))

  files.push({
    path: join(platform.target, 'plugin.json'),
    content: `${JSON.stringify(
      {
        $schema: 'https://agent-plugins.org/schemas/1.0.0/plugin.schema.json',
        name: pluginMeta.name,
        version: pluginMeta.version,
        description: pluginMeta.description,
      },
      null,
      2,
    )}\n`,
  })

  files.push({
    path: join(platform.target, 'README.md'),
    content: [
      `# ${platform.label}`,
      '',
      BANNER,
      '',
      '可攜式 Agent Plugins 格式：根目錄 `plugin.json` + `skills/`。skills 由根目錄的 `skills/` 自動探索，',
      'manifest 不需要 `skills` 欄位。',
      '',
      '## 本機安裝（repo marketplace）',
      '',
      '本 repo 已經有 `.agents/plugins/marketplace.json` 指向 `./plugin/out/openai-plugin`。',
      '重啟 ChatGPT 桌面版後即可在 plugin 清單看到；Codex CLI 用 `/plugins`。',
      '',
      '## 要公開發佈時',
      '',
      'OpenAI 有 Claude plugin 轉投的官方路徑（platform.openai.com/plugins）。轉投前要先處理：',
      '',
      '- `commands/`、`agents/` 必須先轉成 skill（本 plugin 沒用到，無須處理）。',
      '- Claude 專屬字眼要改成中性描述。',
      '- `userConfig` / `${user_config.*}` 不會展開（本 plugin 沒用到）。',
      '- `.mcp.json`、`marketplace.json`、`outputStyles`、`lspServers` 會被丟掉。',
      '- 本 plugin 的 hooks **不會**跟著過去，閘門要靠 skill 內文自行執行。',
      '',
      statusTable(included, excluded, degraded),
      '',
    ].join('\n'),
  })

  return resolveBundleLinks(files, platform.target)
}

function buildClaudeAi(platform: Platform): OutFile[] {
  const { files, included, excluded, degraded } = skillFiles(platform, {
    dir: join(platform.target, 'skills'),
    conditional: false,
    copyRefs: false,
  })

  // 包成 plugin：claude.ai 與 ChatGPT 工作區都能直接從 repo 同步整包安裝，
  // 使用者不必一個一個上傳 zip。手動上傳 zip 仍可用（pnpm plugin:zip）。
  files.push(...bundleSupportFiles(platform.target))

  files.push({
    path: join(platform.target, '.claude-plugin', 'plugin.json'),
    content: `${JSON.stringify(
      {
        name: `${pluginMeta.name}-web`,
        displayName: `${pluginMeta.displayName}（網頁版）`,
        version: pluginMeta.version,
        description: `${pluginMeta.description.replace(/13 個 skill.*$/, '')}網頁版收錄不需要本機 checkout 的 ${included.length} 個流程。`,
        author: pluginMeta.author,
        homepage: pluginMeta.homepage,
        repository: pluginMeta.repository,
        license: pluginMeta.license,
        keywords: pluginMeta.keywords,
      },
      null,
      2,
    )}\n`,
  })

  files.push({
    path: join(platform.target, 'README.md'),
    content: [
      `# ${platform.label}`,
      '',
      BANNER,
      '',
      '## 怎麼裝',
      '',
      '1. Claude.ai → Settings → Capabilities，開啟「Code execution and file creation」。',
      '2. Customize → Skills → 「+」→「Upload a skill」，逐一上傳 zip。',
      '3. zip 的根必須是 skill 資料夾本身（`gh-card.zip → gh-card/SKILL.md`），',
      '   檔案散在 zip 根目錄會上傳失敗。`pnpm plugin:zip` 已經照這個結構打包。',
      '',
      'frontmatter 只留 Agent Skills 標準允許的欄位；多一個欄位 claude.ai 會直接拒絕上傳。',
      '',
      '## 為什麼只有這幾個',
      '',
      'Claude.ai 的 sandbox 有檔案系統也能跑指令，但那是一個空的暫時環境，**不是使用者的 repo**。',
      '需要 checkout、worktree、跑測試的流程搬過來只會讓 agent 宣稱它沒做過的事，所以不收。',
      '完整流程請用 Claude Code 或 Codex。',
      '',
      statusTable(included, excluded, degraded),
      '',
    ].join('\n'),
  })
  return resolveBundleLinks(files, platform.target)
}

function buildCodexHooks(): OutFile[] {
  const claudeHooks = JSON.parse(readFileSync(join(PLUGIN_ROOT, 'hooks', 'hooks.json'), 'utf8')).hooks
  // Codex 的 hook command 以 session cwd 執行，且文件明講不要用相對路徑（Codex 可能從別的目錄啟動）。
  // $REPO_ROOT 只在 skills 探索有定義，hook command 沒有；官方示範用的是 git rev-parse。
  const root = '$(git rev-parse --show-toplevel)/plugin'
  const rewrite = (s: string) => {
    const expanded = s.replaceAll('${CLAUDE_PLUGIN_ROOT}', root)
    // Claude Code 直接執行腳本路徑；Codex 的示範一律帶 interpreter，這裡補上並加引號
    return /^\$\(git rev-parse[^"]*\.sh$/.test(expanded) ? `bash "${expanded}"` : expanded
  }
  const out: Record<string, unknown> = {}
  for (const [event, groups] of Object.entries(claudeHooks as Record<string, any[]>)) {
    out[event] = groups.map((g) => ({
      ...(g.matcher ? { matcher: g.matcher } : {}),
      hooks: g.hooks.map((h: any) => ({ ...h, command: rewrite(h.command) })),
    }))
  }
  return [
    {
      path: '.codex/hooks.json',
      content: `${JSON.stringify({ $comment: BANNER.replace(/<!--|-->/g, '').trim(), hooks: out }, null, 2)}\n`,
    },
    {
      path: '.codex/README.md',
      content: [
        '# Codex 設定',
        '',
        BANNER,
        '',
        '`hooks.json` 與 Claude Code 的 `plugin/hooks/hooks.json` 指向同一批腳本，事件名相同，',
        '所以 pre-pr-gate、stop-quality-gate 等閘門在 Codex 也會實際觸發。',
        '',
        '**第一次使用要先信任**：在 Codex 跑 `/hooks` 檢視並信任這份設定（會對內容做 hash pinning）。',
        '沒信任之前 hooks 不會執行——那就等同沒有閘門，此時 agent 必須自己逐項跑同一批腳本並貼出輸出。',
        '',
        'skills 不在這裡：Codex 掃的是 `.agents/skills/`（見該目錄 README）。',
        '舊版 `.codex/skills/` 不是 Codex 的實際載入路徑，已於 2026-09-21 移除。',
        '',
      ].join('\n'),
    },
  ]
}

function buildRepoMarketplace(): OutFile[] {
  return [
    {
      path: '.agents/plugins/marketplace.json',
      content: `${JSON.stringify(
        {
          name: 'daodao-local',
          plugins: [
            {
              name: pluginMeta.name,
              source: { source: 'local', path: './plugin/out/openai-plugin' },
              policy: { installation: 'AVAILABLE', authentication: 'ON_INSTALL' },
              category: 'Productivity',
            },
          ],
        },
        null,
        2,
      )}\n`,
    },
  ]
}

// ---------------------------------------------------------------- main

const args = process.argv.slice(2)
const checkOnly = args.includes('--check')
const onlyIdx = args.indexOf('--only')
const only = onlyIdx !== -1 ? args[onlyIdx + 1] : null

const hash = (s: string) => createHash('sha256').update(s).digest('hex')

let drift = 0
let written = 0

const jobs: { id: string; label: string; target: string; files: OutFile[] }[] = []

for (const [id, platform] of Object.entries(manifest.platforms)) {
  if (only && only !== id) continue
  if (platform.emit === 'native') continue
  const files =
    platform.emit === 'full-copy'
      ? buildAgentsSkills(platform)
      : platform.emit === 'openai-plugin'
        ? buildOpenAiPlugin(platform)
        : buildClaudeAi(platform)
  jobs.push({ id, label: platform.label, target: platform.target, files })
}

if (!only || only === 'codex-hooks') jobs.push({ id: 'codex-hooks', label: 'Codex hooks', target: '.codex/', files: buildCodexHooks() })
if (!only || only === 'openai-plugin') jobs.push({ id: 'repo-marketplace', label: 'Repo marketplace', target: '.agents/plugins/', files: buildRepoMarketplace() })

if (errors.length) {
  console.error('✗ canonical 有問題，先修好再產出：\n')
  for (const e of errors) console.error(`  - ${e}`)
  process.exit(1)
}

/**
 * 產出前會整個刪掉 target 目錄。platforms.json 是手改的，target 打錯一個字就可能
 * 刪掉 canonical（例如把 claude-code 的 emit 從 native 改掉，target 是 `plugin/`，
 * 整個 plugin/skills 就沒了）。刪除前一律先過這關。
 */
function assertSafeToWipe(target: string) {
  const abs = resolve(REPO_ROOT, target)
  const rel = relative(REPO_ROOT, abs)

  if (rel === '' || rel.startsWith('..')) {
    throw new Error(`拒絕刪除「${target}」：不在 repo 內，或就是 repo 根目錄`)
  }
  // canonical 的來源目錄一律不可當作產出目標
  const protectedRoots = ['plugin/skills', 'plugin/hooks', 'plugin/templates', 'plugin/docs', 'plugin/scripts', '.claude-plugin', '.git']
  for (const guarded of protectedRoots) {
    const guardedAbs = resolve(REPO_ROOT, guarded)
    if (abs === guardedAbs || guardedAbs.startsWith(`${abs}/`) || abs.startsWith(`${guardedAbs}/`)) {
      throw new Error(`拒絕刪除「${target}」：會波及 canonical 來源 ${guarded}`)
    }
  }
}

for (const job of jobs) {
  const targetAbs = resolve(REPO_ROOT, job.target)
  if (!checkOnly && job.id !== 'codex-hooks' && job.id !== 'repo-marketplace' && existsSync(targetAbs)) {
    assertSafeToWipe(job.target)
    rmSync(targetAbs, { recursive: true, force: true })
  }
  for (const f of job.files) {
    const abs = resolve(REPO_ROOT, f.path)
    if (checkOnly) {
      const current = existsSync(abs) ? readFileSync(abs, 'utf8') : null
      if (current === null || hash(current) !== hash(f.content)) {
        console.error(`✗ 產物過期：${f.path}`)
        drift++
      }
      continue
    }
    mkdirSync(dirname(abs), { recursive: true })
    writeFileSync(abs, f.content)
    written++
  }
  if (!checkOnly) console.log(`✓ ${job.label} → ${job.target}（${job.files.length} 檔）`)
}

if (checkOnly) {
  if (drift > 0) {
    console.error(`\n${drift} 個產物與 plugin/skills/ 不同步。跑 \`pnpm plugin:build\` 後重新 commit。`)
    process.exit(1)
  }
  console.log('✓ 所有平台產物與 canonical 同步')
} else {
  console.log(`\n完成，共寫入 ${written} 個檔案。`)
}
